### ISSUE TITLE
Remediation Script Question

### ISSUE THREAD

**Issue by ghost** [engrit-illinois/Compare-AssignmentRevisions#1]
Hi,

Thanks so much for the report, I really appreciate it. I noticed that on one of the Microsoft threads you referenced someone shared a sort of remediation script that seems to trigger the schedule to re-evaluate stuff. I was wondering if you had built something similar to it? I noticed in one of your replies you shared some sort of remediation before you replied with this report.

**Comment by mmseng** [comment]
Hmm, it's been quite a while since I've needed (or bothered) to do any remediation on individual machines, so much of this has fallen out of my brain. I've read through my MS thread posts again to try to remember what I can.

At least for the problem of apps not showing up in Software Center, the traditional method we've used is the bit in the Trigger-Assignment() function from my code in the MS thread.

That function takes a specific assignment ID and triggers it (TBH I'm not sure what this "trigger" is actually doing, but this usually seems to make the relevant app show up in SC). The rest of the code only calls this trigger on assignments if it detects that the assignment is missing a deployment type (or if the $TRIGGER_ALL boolean is true).

In practice, when I do come across this situation, I tend to just reinstall the client. Just seems more proper, and handles any other client health issues that may be present. However if you want to try it out you could either use the code I posted in the MS thread, or just use this simplified excerpt, which calls that trigger for every single assignment, regardless:

```powershell
$Assignments = (Get-WmiObject -Namespace root\ccm\Policy\Machine -Query "Select * FROM CCM_ApplicationCIAssignment").AssignmentID
ForEach ($Assignment in $Assignments) {
    $Trigger = [wmiclass] "\root\ccm:SMS_Client"
    $Trigger.TriggerSchedule("$Assignment")
    Start-Sleep 1
}
```

FWIW, I keep this snippet for reference along with several other random MECM-related snippets here (it's the fourth example in this script full of random stuff): https://github.com/engrit-illinois/org-shared-mecm-deployments/blob/main/org-shared-deployments-misc.ps1

TBH I don't know whether this really "solves" the underlying issue or not. But it's definitely handy on occasion if you're in a pinch and just want SC to get populated.

**Comment by ghost** [comment]
That snippet seems to be very handy indeed, thanks for sharing I'll definitely follow your advice to reinstall the client. With your script I identified about ~600 computers that seem to have some sort of mismatch in the assignments.

**Comment by mmseng** [comment]
Glad it's useful. If you haven't, review my notes in the Interpretation section of the readme for some help with reading the data.

Cheers.
